# Generated by Django 5.2.1 on 2025-05-30 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jogador',
            old_name='Time',
            new_name='time',
        ),
    ]
