# Generated by Django 5.2.1 on 2025-05-30 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do time')),
                ('capitao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='players.jogador')),
            ],
            options={
                'verbose_name': 'Time',
                'verbose_name_plural': 'Times',
                'db_table': 'time',
            },
        ),
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do time')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.endereco', verbose_name='Endereço')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadios', to='teams.time')),
            ],
            options={
                'verbose_name': 'Estadio',
                'verbose_name_plural': 'estadios',
                'db_table': 'estadio',
            },
        ),
    ]
