# Generated by Django 5.2.1 on 2025-05-30 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_rename_time_jogador_time'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='capitao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='times', to='players.jogador'),
        ),
    ]
