# Generated by Django 5.2.1 on 2025-06-02 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_alter_time_capitao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome do campeoato')),
            ],
            options={
                'verbose_name': 'Campeonato',
                'verbose_name_plural': 'Campeonatos',
                'db_table': 'campeonato',
            },
        ),
        migrations.CreateModel(
            name='Edicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championship.campeonato')),
                ('time', models.ManyToManyField(to='teams.time')),
            ],
            options={
                'verbose_name': 'Edição',
                'verbose_name_plural': 'Edições',
                'db_table': 'edicao',
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='Data')),
                ('placar_mandante', models.IntegerField(verbose_name='Placar do mandante')),
                ('placar_visitante', models.IntegerField(verbose_name='Placar do visitante')),
                ('edicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championship.edicao')),
                ('time_mandante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_mandante', to='teams.time')),
                ('time_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_visitante', to='teams.time')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
                'db_table': 'partida',
            },
        ),
    ]
