# Generated by Django 5.2.1 on 2025-05-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lagradouro', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('cidade', models.CharField(max_length=200, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
            ],
            options={
                'verbose_name': 'Endereco',
                'verbose_name_plural': 'enderecos',
                'db_table': 'endereco',
            },
        ),
    ]
